version: '3'

services:
  mssql:
    build: .
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Test_1234
      MSSQL_AGENT_ENABLED: true
    image: mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Test_1234 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
         
       